import type { LanguageMessages } from 'vanilla-press';

export default {
  'zh-CN': {
    menu: {
      home: '首页',
      components: '组件',
      documents: '文档中心',
      learn: '吉木学院',
    },
    sidebar: {
      quickStart: '快速开始',

      componentArchitecture: '组件架构',
      designStandard: '设计标准',
      defineComponent: '定义组件',
      view: '视图',
      scheduler: '调度器',
      animation: '动画',

      cssArchitecture: 'CSS 架构',
      tokens: '令牌',
      colorTokens: '色彩令牌',
      colorSystem: '色彩系统',

      interactionComponents: '交互组件',
      modal: '模态框',
      form: '表单',
      offcanvas: '侧滑面板',
      accordion: '折叠面板',
      tabs: '选项卡',
      flow: '流程',
      swiper: '轮播图',
      pagination: '分页',
      menu: '菜单',
      toc: '目录',
      toast: '通知',
      drop: '下拉容器',
      tooltip: '提示',
      theme: '主题',
      parabola: '抛物线',
      popup: '弹窗',
      sticky: '固定',
      icons: '图标',
      validator: '表单验证',

      staticComponents: '静态组件',
      container: '容器',
      layout: '布局',
      fonts: '字体',
      button: '按钮',
      avatar: '头像',
      badge: '徽章',
      tag: '标签',
      tip: '提示',
      card: '卡片',
      breadcrumb: '面包屑',
      editor: '编辑器',

      utilitiesFunctions: '工具函数',
      browser: '浏览器',
      event: '事件',
      timer: '定时器',
      refs: '引用',
      state: '状态',
      object: '对象',
      Types: '类型定义',

      relatedLibraries: '相关库',
      others: '其他',
      changelog: '变更日志',
    },
    mobile: {
      navigation: '导航',
      toc: '目录',
    },
    search: {
      button: '搜索',
      title: '搜索文档',
      placeholder: '输入关键词...',
      empty: '没有找到匹配内容',
      hint: '输入关键词搜索标题和正文',
    },
    prevNext: {
      previous: '上一页',
      next: '下一页',
    },
    theme: {
      button: '主题',
    },
    auth: {
      login: '登录',
    },
  },
  en: {
    menu: {
      home: 'Home',
      components: 'Components',
      documents: 'Documents',
      learn: 'Learn',
    },
    sidebar: {
      quickStart: 'Quick Start',

      componentArchitecture: 'Component Architecture',
      designStandard: 'Design Standard',
      defineComponent: 'Define Component',
      view: 'View',
      scheduler: 'Scheduler',
      animation: 'Animation',

      cssArchitecture: 'CSS Architecture',
      tokens: 'Tokens',
      colorTokens: 'Color Tokens',
      colorSystem: 'Color System',

      interactionComponents: 'Interaction Components',
      modal: 'Modal',
      form: 'Form',
      offcanvas: 'Offcanvas',
      accordion: 'Accordion',
      tabs: 'Tabs',
      flow: 'Flow',
      swiper: 'Swiper',
      pagination: 'Pagination',
      menu: 'Menu',
      toc: 'TOC',
      toast: 'Toast',
      drop: 'Drop',
      tooltip: 'Tooltip',
      theme: 'Theme',
      parabola: 'Parabola',
      popup: 'Popup',
      sticky: 'Sticky',
      icons: 'Icons',
      validator: 'Validator',

      staticComponents: 'Static Components',
      container: 'Container',
      layout: 'Layout',
      fonts: 'Fonts',
      button: 'Button',
      avatar: 'Avatar',
      badge: 'Badge',
      tag: 'Tag',
      tip: 'Tip',
      card: 'Card',
      breadcrumb: 'Breadcrumb',
      editor: 'Editor',

      utilitiesFunctions: 'Utilities Functions',
      browser: 'Browser',
      event: 'Event',
      timer: 'Timer',
      refs: 'Refs',
      state: 'State',
      object: 'Object',
      Types: 'Types',

      relatedLibraries: 'Related Libraries',
      others: 'Others',
      changelog: 'Changelog',
    },
    mobile: {
      navigation: 'Navigation',
      toc: 'On this page',
    },
    search: {
      button: 'Search',
      title: 'Search Docs',
      placeholder: 'Type keywords...',
      empty: 'No results found',
      hint: 'Search titles and page content',
    },
    prevNext: {
      previous: 'Previous',
      next: 'Next',
    },
    theme: {
      button: 'Theme',
    },
    auth: {
      login: 'Login',
    },
  },
} satisfies LanguageMessages;
